language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - ruby-head
  - jruby-head
  - ree
  - 2.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx-19mode
    - rvm: jruby-18mode

script:
  - bundle exec rake spec

env: YOGI_ENV=test
